[package]
name = "gfx_window_metal"
version = "0.4.0"
description = "Metal window for gfx-rs"
homepage = "https://github.com/gfx-rs/gfx"
repository = "https://github.com/gfx-rs/gfx"
keywords = ["graphics", "gamedev"]
license = "Apache-2.0"
authors = ["The Gfx-rs Developers"]
documentation = "https://docs.rs/gfx_window_metal"
workspace = "../../.."

[lib]
name = "gfx_window_metal"

[dependencies]
log = "0.3"
cocoa = "0.9"
core-foundation = "0.3"
core-graphics = "0.8"
objc = "0.2"
io-surface = "0.7"
winit = "0.7"
metal-rs = "0.4"
gfx_core = { path = "../../core", version = "0.10" }
gfx_device_metal = { path = "../../backend/metal", version = "0.3" }
scopeguard = "0.3"
