# Copyright 2016 The Gfx-rs Developers.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "gfx_window_metal"
version = "0.4.0"
description = "Metal window for gfx-rs"
homepage = "https://github.com/gfx-rs/gfx"
repository = "https://github.com/gfx-rs/gfx"
keywords = ["graphics", "gamedev"]
license = "Apache-2.0"
authors = ["The Gfx-rs Developers"]
documentation = "https://docs.rs/gfx_window_metal"

[lib]
name = "gfx_window_metal"

[dependencies]
log = "0.3"
cocoa = "0.9"
core-foundation = "0.3"
core-graphics = "0.8"
objc = "0.2"
io-surface = "0.7"
winit = "0.7"
metal-rs = "0.4"
gfx_core = { path = "../../core", version = "0.7" }
gfx_device_metal = { path = "../../backend/metal", version = "0.3" }
scopeguard = "0.3"
