all: build

build:
	(cd triangle && cargo build)
	(cd cube && cargo build)
	(cd gl-init && cargo build)
	(cd terrain && cargo build)

update:
	(cd triangle && cargo update)
	(cd cube && cargo update)
	(cd gl-init && cargo update)
	(cd terrain && cargo update)

clean:
	(cd triangle && cargo clean)
	(cd cube && cargo clean)
	(cd gl-init && cargo clean)
	(cd terrain && cargo clean)
