all: build

build:
	(cd triangle && cargo build)
	(cd cube && cargo build)
	(cd draw_list && cargo build)

update:
	(cd triangle && cargo update)
	(cd cube && cargo update)
	(cd draw_list && cargo update)

clean:
	(cd triangle && cargo clean)
	(cd cube && cargo clean)
	(cd draw_list && cargo clean)
