[package]
name = "gfx_window_glfw"
version = "0.15.0"
description = "GLFW window for gfx-rs"
homepage = "https://github.com/gfx-rs/gfx"
repository = "https://github.com/gfx-rs/gfx"
keywords = ["graphics", "gamedev"]
license = "Apache-2.0"
authors = ["The Gfx-rs Developers"]
readme = "README.md"
documentation = "https://docs.rs/gfx_window_glfw"
workspace = "../../.."

[lib]
name = "gfx_window_glfw"

[dependencies]
glfw = "0.15"
gfx_core = { path = "../../core", version = "0.10" }
gfx_device_gl = { path = "../../backend/gl", version = "0.14" }

# Currently there is an issue with cargo and dev-dependencies:
# https://github.com/rust-lang/cargo/issues/860
# TODO: move gfx to [dev-dependencies] once it gets resolved.
gfx = { path = "../../render", version = "0.16" }
